### PR TITLE
Testlogging

### PR DESCRIPTION
**Pull request by gandelman-a**

### CODE REVIEW

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by rattboi** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gandelman-a** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Review by ConsoleCatzirl — APPROVED** [review]

**Pull request merged**
