### PR TITLE
Initial test script

### PR DESCRIPTION
**Pull request by omgjlk**
Signed-off-by: Jesse Keating <jkeating@j2solutions.net>

### CODE REVIEW

**Review by rattboi — DISMISSED** [review]
SO TRUE

**Comment by omgjlk** [comment]
gate-recheck

**Review by rattboi — APPROVED** [review]
too true

**Comment by omgjlk** [comment]
gate-recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/gate_github/BonnyCI/sandbox/15/1486169733.36/bonnyci-run-gate : FAILURE in 11s

**Pull request merged**
