### PR TITLE
Herp DORP

### PR DESCRIPTION
**Pull request by rattboi**
Test

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- echo-true : RETRY_LIMIT
- noop : SUCCESS

**Comment by anne-bonny** [comment]
Build failed.

- echo-true : RETRY_LIMIT
- noop : SUCCESS

**Comment by anne-bonny** [comment]
Build failed.

- echo-true : NOT_REGISTERED
- noop : SUCCESS

**Comment by omgjlk** [comment]
recheck

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by omgjlk** [comment]
recheck

**Comment by gandelman-a** [comment]
recheck

**Review by gandelman-a — DISMISSED** [review]

**Comment by gandelman-a** [comment]
Hmm so after tests pass, and giving this a postiive review, the webhook is received but the gate does not trigger...
 
```
2017-02-10 20:29:25,501 DEBUG zuul.GithubWebhookListener: Github Webhook Received.
2017-02-10 20:29:25,502 DEBUG zuul.GithubWebhookListener: X-Github-Event: pull_request_review
2017-02-10 20:29:26,228 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4927 reset: 1486761158
2017-02-10 20:29:26,228 DEBUG zuul.GithubWebhookListener: Scheduling github event: pr-review
2017-02-10 20:29:26,228 DEBUG zuul.Scheduler: Adding trigger event: <TriggerEvent pr-review BonnyCI/sandbox master 5,1ecb8852510ca191c7945e0af22b9b86081c0b82>
2017-02-10 20:29:26,229 DEBUG zuul.Scheduler: Run handler awake
2017-02-10 20:29:26,229 DEBUG zuul.Scheduler: Fetching trigger event
2017-02-10 20:29:26,229 DEBUG zuul.Scheduler: Processing trigger event <TriggerEvent pr-review BonnyCI/sandbox master 5,1ecb8852510ca191c7945e0af22b9b86081c0b82>
2017-02-10 20:29:26,230 DEBUG zuul.Scheduler: Done adding trigger event: <TriggerEvent pr-review BonnyCI/sandbox master 5,1ecb8852510ca191c7945e0af22b9b86081c0b82>
2017-02-10 20:29:26,680 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4925 reset: 1486761158
2017-02-10 20:29:27,109 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4923 reset: 1486761158
2017-02-10 20:29:27,449 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4921 reset: 1486761158
2017-02-10 20:29:27,791 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4919 reset: 1486761158
2017-02-10 20:29:28,193 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4917 reset: 1486761158
2017-02-10 20:29:28,504 DEBUG zuul.GithubConnection: GitHub API rate limit remaining: 4915 reset: 1486761158
2017-02-10 20:29:28,690 DEBUG zuul.GithubUser: GitHub API rate limit remaining: 4914 reset: 1486761158
2017-02-10 20:29:28,690 DEBUG zuul.IndependentPipelineManager: Starting queue processor: check_github
2017-02-10 20:29:28,690 DEBUG zuul.IndependentPipelineManager: Finished queue processor: check_github (changed: False)
2017-02-10 20:29:28,690 DEBUG zuul.DependentPipelineManager: Starting queue processor: gate_github
2017-02-10 20:29:28,691 DEBUG zuul.DependentPipelineManager: Finished queue processor: gate_github (changed: False)
2017-02-10 20:29:28,691 DEBUG zuul.Scheduler: Run handler sleeping
```

**Review by gandelman-a — APPROVED** [review]

**Pull request merged**
