### PR TITLE
pull one

### PR DESCRIPTION
**Pull request by gandelman-a**

### CODE REVIEW

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/sandbox/22/1487144140.7/bonnyci-run-check : POST_FAILURE in 12s

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/sandbox/22/1487144588.29/bonnyci-run-check : POST_FAILURE in 12s

**Comment by jamielennox** [comment]
recheck

**Comment by jamielennox** [comment]
recheck

**Comment by jamielennox** [comment]
recheck

**Comment by jamielennox** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://192.168.0.14/check_github/BonnyCI/sandbox/22/1488401299.82/bonnyci-run-check : NOT_REGISTERED

**Comment by jamielennox** [comment]
Duplicate of #20 and causing problems

**Pull request closed without merging**
