### PR TITLE
Foo

### PR DESCRIPTION
**Pull request by gandelman-a**

### CODE REVIEW

**Comment by omgjlk** [comment]
recheck

**Comment by jamielennox** [comment]
recheck

**Review by omgjlk — DISMISSED** [review]
I want changes here.

**Review by pschwartz — APPROVED** [review]

**Comment by jamielennox** [comment]
wtf is a :shipit:

**Review by omgjlk — APPROVED** [review]

**Review by omgjlk — CHANGES_REQUESTED** [review]
I need a change.

**Comment by omgjlk** [comment]
recheck

**Review by omgjlk — CHANGES_REQUESTED** [review]
Sure why not

**Review by omgjlk — APPROVED** [review]

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/sandbox/13/1486167926.99/bonnyci-run-check : FAILURE in 11s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Pull request closed without merging**
