### PR TITLE
Pull2

### PR DESCRIPTION
**Pull request by gandelman-a**

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/sandbox/21/1486753681.84/bonnyci-run-check : FAILURE in 48s

**Comment by gandelman-a** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/sandbox/21/1486753787.33/bonnyci-run-check : FAILURE in 48s

**Comment by gandelman-a** [comment]
recheck

**Pull request closed without merging**
