### PR TITLE
Update bourbontype

### PR DESCRIPTION
**Pull request by ConsoleCatzirl**
Add Four Roses

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build succeeded.

- telnet://192.168.3.234:19885 : SUCCESS in 3s
- noop : SUCCESS

**Review by omgjlk — APPROVED** [review]
I approve of this review.

**Review by ConsoleCatzirl — COMMENTED** [review]
:-1:

**Review by rattboi — DISMISSED** [review]
I don't like this kind of bourbon. Change it to something I like.

**Comment by anne-bonny** [comment]
Build succeeded.

- telnet://192.168.3.234:19885 : SUCCESS in 3s
- noop : SUCCESS

**Review by jkomg — CHANGES_REQUESTED** [review]
testing for ilk

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by ConsoleCatzirl** [comment]
recheck

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by anne-bonny** [comment]
Build succeeded.

- telnet://192.168.3.235:19885 : SUCCESS in 3s
- noop : SUCCESS

**Pull request merged**
